make: major1.o power.o reverse.o replace.o palindrome.o
	cc major1.o power.o reverse.o replace.o palindrome.o
major1.o: major1.h
	cc -c major1.c
power.o: power.c
	cc -c power.c
reverse.o: reverse.c
	cc -c reverse.c
replace.o: replace.c
	cc -c replace.c
palindrome.o: palindrome.c
	cc -c palindrome.c
run:
	./a.out
clean:
	rm a.out*.o